create table ranking (id int4 generated by default as identity, dificuldade int4, pontuacao int4, user_id int4, primary key (id));
create table usuario (id int4 generated by default as identity, pwd varchar(255), username varchar(255), primary key (id));
alter table if exists ranking add constraint FKgkqbt2yml8kuyx5o7y84c8o4v foreign key (user_id) references usuario;
create table ranking (id int4 generated by default as identity, dificuldade int4, pontuacao int4, user_id int4, primary key (id));
create table usuario (id int4 generated by default as identity, pwd varchar(255), username varchar(255), primary key (id));
alter table if exists ranking add constraint FKgkqbt2yml8kuyx5o7y84c8o4v foreign key (user_id) references usuario;
